# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ef0179e4-0c03-41c2-9b9b-2f293dba5c2d'
  imageRepository: 'pythonazuredevopscontainerized'
  containerRegistry: 'scrumban.azurecr.io'
  #dockerfilePath: './Dockerfile'
  ACR_PASSWORD: ''
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  webApp: 'Python-AzureDevOps-Containerized'
  azureSubscription: 'Scrumbanai Container App'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: deploy_container_app
  displayName: Deploy BuildImage to Container App
  dependsOn: [Build]
  jobs:
    - job: BuildDeploy
      steps:
        - task: AzureContainerApps@1  # Use AzureContainerApps@1 task
          displayName: Build and Deploy to Container App
          inputs:
            azureSubscription: 'Scrumbanai Container App'  # Replace with your subscription name
            acrName: 'Scrumban'  # Replace with your ACR name
            acrUsername: 'Scrumban'  # Replace with your ACR username
            acrPassword: '$(ACR_PASSWORD)'  # Reference password from pipeline variable
           
            dockerfilePath: '$(Build.SourcesDirectory)/app/' # Replace with your Dockerfile path
            imageToBuild: 'Dockerfile'                    # Replace with your Dockerfile name
            imageToDeploy: 'scrumban.azurecr.io/pythonazuredevopscontainerized:$(tag)'  # Use existing image
            containerAppName: 'scrumbancontainer'
            resourceGroup: 'Scrumban_Docker'
